#!/usr/bin/env node
// Markdown reflow checker / fixer.
//
// Why this exists
// ---------------
//
// `.markdownlint-cli2.jsonc` documents the project's stated convention:
// "Long prose lines are intentional. Hard-wrapping at 80 columns makes
// diffs noisier and discourages writing in paragraphs. We rely on
// editor soft-wrap instead." The convention was historically
// unenforced — markdownlint has no rule for "no hard-wrap in prose"
// because the question is harder than line length alone.
//
// This script is the enforcement. It implements the inverse of a
// hard-wrapper: each prose paragraph is collapsed onto a single line.
// Code fences, headings, tables, blockquotes, list items (with their
// continuations), HTML comments, and YAML frontmatter blocks are
// preserved verbatim.
//
// Modes
// -----
//
//   --write   (default)  reflow files in place. Used to fix existing
//                        files or after pasting hard-wrapped text.
//   --check              read-only; print files that would change and
//                        exit 1 on any drift. Used by `pnpm verify`.
//
// File set
// --------
//
// Defaults to every `.md` under the repo, excluding the same paths
// `.markdownlint-cli2.jsonc` ignores (`node_modules`, `dist`,
// `dist-ui`, `coverage`, the auto-generated `docs/reference/`, and the
// changesets-managed `CHANGELOG.md` files). Pass file paths as
// positional args to override the default set.

import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// Excluded directory names — pruned during the directory walk, so the
// walker never descends into them. Mirrors the `ignores` list in
// `.markdownlint-cli2.jsonc` and `biome.json`. `.changeset/` is
// deliberately NOT pruned: it contains user-authored markdown that
// should be reflowed before merge so the generated CHANGELOG entry
// inherits the long-line format.
const PRUNED_DIRS = new Set(['node_modules', 'dist', 'dist-ui', 'coverage', '.git']);

// Excluded file names anywhere in the tree.
const EXCLUDED_FILE_BASENAMES = new Set([
  'CHANGELOG.md', // changesets-managed; historical entries are shipped releases.
]);

// `docs/reference/` is auto-generated by `scripts/docs.mjs`. Excluded
// because reflow vs the registry-rendered output is the source of
// truth's job, not ours.
const EXCLUDED_RELATIVE_DIRS = new Set([resolve(ROOT, 'docs/reference')]);

const CODE_FENCE_RE = /^\s*(```|~~~)/;
const HEADING_RE = /^\s*#{1,6}\s/;
const LIST_ITEM_RE = /^(\s*)([-*+]|\d+\.)\s+/;
const TABLE_RE = /^\s*\|/;
const HR_RE = /^\s*([-*_])\s*\1\s*\1[\s\1]*$/;
const HARD_BREAK = '  '; // two trailing spaces = markdown hard break

function isBlank(line) {
  return line.trim() === '';
}

function isBlockBreak(line) {
  if (isBlank(line)) return true;
  if (HEADING_RE.test(line)) return true;
  if (CODE_FENCE_RE.test(line)) return true;
  if (TABLE_RE.test(line)) return true;
  if (HR_RE.test(line)) return true;
  if (line.trimStart().startsWith('>')) return true;
  if (LIST_ITEM_RE.test(line)) return true;
  return false;
}

function stripQuoteMarker(line) {
  const s = line.trimStart();
  if (s.startsWith('> ')) return s.slice(2);
  if (s.startsWith('>')) return s.slice(1);
  return s;
}

function reflow(text) {
  const lines = text.split('\n');
  const out = [];
  let i = 0;
  let inFence = false;
  let inHtmlComment = false;

  // YAML frontmatter — pass through verbatim if present at file start.
  // Each `key: value` line must stay on its own line; joining them
  // produces invalid YAML.
  if (lines.length > 0 && lines[0].trim() === '---') {
    out.push(lines[0]);
    let j = 1;
    while (j < lines.length && lines[j].trim() !== '---') {
      out.push(lines[j]);
      j += 1;
    }
    if (j < lines.length) {
      out.push(lines[j]); // closing ---
      j += 1;
    }
    i = j;
  }

  while (i < lines.length) {
    const line = lines[i];

    if (CODE_FENCE_RE.test(line)) {
      out.push(line);
      inFence = !inFence;
      i += 1;
      continue;
    }
    if (inFence) {
      out.push(line);
      i += 1;
      continue;
    }

    if (inHtmlComment) {
      out.push(line);
      if (line.includes('-->')) inHtmlComment = false;
      i += 1;
      continue;
    }
    if (line.includes('<!--') && !line.includes('-->')) {
      out.push(line);
      inHtmlComment = true;
      i += 1;
      continue;
    }

    if (isBlank(line)) {
      out.push(line);
      i += 1;
      continue;
    }

    if (HEADING_RE.test(line)) {
      out.push(line.replace(/\s+$/u, ''));
      i += 1;
      continue;
    }

    if (HR_RE.test(line)) {
      out.push(line.replace(/\s+$/u, ''));
      i += 1;
      continue;
    }

    if (TABLE_RE.test(line)) {
      out.push(line.replace(/\s+$/u, ''));
      i += 1;
      continue;
    }

    if (line.trimStart().startsWith('>')) {
      let buf = stripQuoteMarker(line);
      let j = i + 1;
      while (j < lines.length) {
        const nxt = lines[j];
        if (!nxt.trimStart().startsWith('>')) break;
        if (nxt.trim() === '>' || nxt.trim() === '>>') break;
        if (buf.endsWith(HARD_BREAK)) break;
        buf = `${buf} ${stripQuoteMarker(nxt)}`;
        j += 1;
      }
      out.push(`> ${buf}`);
      i = j;
      continue;
    }

    const m = LIST_ITEM_RE.exec(line);
    if (m) {
      const contentCol = m[0].length;
      let buf = line.replace(/\s+$/u, '');
      let j = i + 1;
      while (j < lines.length) {
        const nxt = lines[j];
        if (isBlank(nxt)) break;
        if (nxt.endsWith(HARD_BREAK)) break;
        if (
          HEADING_RE.test(nxt) ||
          CODE_FENCE_RE.test(nxt) ||
          TABLE_RE.test(nxt) ||
          HR_RE.test(nxt) ||
          nxt.trimStart().startsWith('>')
        ) {
          break;
        }
        // ANY further list marker breaks the join — nested items
        // are themselves list items and must be processed by the
        // main loop one level deeper, not glued into the parent.
        // This catches both sibling/shallower items (next bullet)
        // and nested items (sub-bullet under this one).
        if (LIST_ITEM_RE.test(nxt)) break;
        const nxtIndent = nxt.length - nxt.trimStart().length;
        if (nxtIndent < contentCol) break;
        buf = `${buf} ${nxt.trim()}`;
        j += 1;
      }
      out.push(buf);
      i = j;
      continue;
    }

    // Plain prose
    let buf = line.replace(/\s+$/u, '');
    let j = i + 1;
    while (j < lines.length) {
      const nxt = lines[j];
      if (isBlockBreak(nxt)) break;
      if (buf.endsWith(HARD_BREAK)) break;
      buf = `${buf} ${nxt.trim()}`;
      j += 1;
    }
    out.push(buf);
    i = j;
  }

  return out.join('\n');
}

function isExcluded(absPath) {
  if (EXCLUDED_FILE_BASENAMES.has(absPath.split('/').pop() ?? '')) return true;
  for (const dir of EXCLUDED_RELATIVE_DIRS) {
    if (absPath === dir || absPath.startsWith(`${dir}/`)) return true;
  }
  return false;
}

function walkMarkdown(rootDir) {
  const out = [];
  const entries = readdirSync(rootDir);
  for (const name of entries) {
    if (PRUNED_DIRS.has(name)) continue;
    const abs = resolve(rootDir, name);
    let st;
    try {
      st = statSync(abs);
    } catch {
      continue;
    }
    if (st.isDirectory()) {
      out.push(...walkMarkdown(abs));
    } else if (st.isFile() && abs.endsWith('.md') && !isExcluded(abs)) {
      out.push(abs);
    }
  }
  return out;
}

function parseArgs(argv) {
  const args = argv.slice(2);
  let mode = 'write';
  const files = [];
  for (const arg of args) {
    if (arg === '--check') {
      mode = 'check';
    } else if (arg === '--write') {
      mode = 'write';
    } else if (arg.startsWith('--')) {
      throw new Error(`unknown flag: ${arg}. Use --write (default) or --check.`);
    } else {
      files.push(resolve(arg));
    }
  }
  return { mode, files };
}

function main(argv) {
  const { mode, files: explicitFiles } = parseArgs(argv);
  const files = explicitFiles.length > 0 ? explicitFiles : walkMarkdown(ROOT);
  const drifted = [];
  let touched = 0;

  for (const file of files) {
    const text = readFileSync(file, 'utf8');
    const reflowed = reflow(text);
    if (reflowed === text) continue;

    if (mode === 'write') {
      writeFileSync(file, reflowed, 'utf8');
      touched += 1;
      process.stdout.write(`reflowed: ${relative(ROOT, file)}\n`);
    } else {
      drifted.push(file);
    }
  }

  if (mode === 'check') {
    if (drifted.length === 0) {
      process.stdout.write(`reflow check passed (${files.length} files clean).\n`);
      return 0;
    }
    process.stderr.write('the following files are hard-wrapped and need reflow:\n');
    for (const file of drifted) {
      process.stderr.write(`  ${relative(ROOT, file)}\n`);
    }
    process.stderr.write('\nfix locally with: pnpm docs:reflow\n');
    return 1;
  }

  if (touched === 0) {
    process.stdout.write(`no changes (${files.length} files already in long-line form).\n`);
  } else {
    process.stdout.write(`reflowed ${touched} of ${files.length} files.\n`);
  }
  return 0;
}

process.exit(main(process.argv));
